### ISSUE TITLE
Show and Tell: Automations/Dashboard examples

### ISSUE THREAD

**Issue by catatonicChimp** [bremor/public_transport_victoria#28]
Just making this here for people to show off automations and dashboards to go with the extension

Increase default update rate for peak times:

```
alias: Update Trains
description: ""
mode: single
triggers:
  - minutes: /1
    trigger: time_pattern
conditions:
  - condition: or
    conditions:
      - condition: time
        after: "06:30:00"
        before: "09:00:00"
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: time
        after: "15:30:00"
        before: "18:00:00"
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
actions:
  - action: homeassistant.update_entity
    data:
      entity_id:
        - sensor.xxxxxx_line_to_city_flinders_street_from_yyyyyy_station_0
        - sensor.xxxxxx_line_to_city_flinders_street_from_yyyyyy_station_1
        - sensor.xxxxxx_line_to_city_flinders_street_from_yyyyyy_station_2
        - sensor.xxxxxx_line_to_city_flinders_street_from_yyyyyy_station_3
        - sensor.xxxxxx_line_to_city_flinders_street_from_yyyyyy_station_4
        - sensor.xxxxxx_line_to_city_flinders_street_from_yyyyyy_station_5
```

Next Train Announcement (Using sayTTS and DVA5 to generate the chime/first part of message
DVA5: https://github.com/jaboles/DVA5/releases
```
alias: Train Announcement
description: ""
triggers:
  - entity_id:
      - sensor.xxxx_line_to_city_flinders_street_from_yyyy_station_0
    attribute: run_id
    trigger: state
conditions:
  - condition: time
    after: "07:00:00"
    before: "09:00:00"
actions:
  - action: chime_tts.say
    metadata: {}
    data:
      chime_path: /media/ChimeRoute.mp3
      message: >-
        {% set estimated_departure =
        as_timestamp(state_attr('sensor.xxxx_line_to_city_flinders_street_from_yyyy_station_0',
        'estimated_departure_utc')) %}

        {% set estimated_departure_local =
        as_local(as_datetime(state_attr('sensor.xxxx_line_to_city_flinders_street_from_yyyy_station_0',
        'estimated_departure_utc'))).strftime('%H:%M %p') %}

        {% set scheduled_departure =
        as_timestamp(state_attr('sensor.xxxx_line_to_city_flinders_street_from_yyyy_station_0',
        'scheduled_departure_utc')) %}

        {% set scheduled_departure_local =
        as_local(as_datetime(state_attr('sensor.xxxx_line_to_city_flinders_street_from_yyyy_station_0',
        'scheduled_departure_utc'))).strftime('%H:%M %p') %}


        {% set delay_minutes = ((estimated_departure - scheduled_departure) //
        60) | int %}

        {% set minutes_until_departure = ((estimated_departure -
        as_timestamp(now())) // 60) | int %}

        {% set time_difference = estimated_departure - scheduled_departure %}

        {% if time_difference > 0 and time_difference <= 60 %}
          is delayed by {{ delay_minutes }} minute, and will now depart in {{ minutes_until_departure }} minutes at {{ estimated_departure_local }}.
        {% elif time_difference > 60 %}
          is delayed by {{ delay_minutes }} minutes, and will now depart in {{ minutes_until_departure }} minutes at {{ estimated_departure_local }}.
        {% elif time_difference < 0 and time_difference >= -60 %}
          is early by {{ delay_minutes }} minute, and will now depart in {{ minutes_until_departure }} minute at {{ estimated_departure_local }}.    
        {% elif time_difference < -60 %}
          is early by {{ delay_minutes }} minutes, and will now depart in {{ minutes_until_departure }} minutes at {{ estimated_departure_local }}.    
        {% else %}
          is scheduled to depart in {{ minutes_until_departure }} minutes at {{ estimated_departure_local }}.
        {% endif %}
      offset: 0
      tts_platform: cloud
      language: en-AU
      voice: ElsieNeural
      join_players: true
      unjoin_players: true
      cache: false
      fade_audio: true
    target:
      entity_id: media_player.study
```
